### ISSUE TITLE
cr_import_xml() failure when Importing Report From Repository

### ISSUE THREAD

**Issue by michael-milette** [jleyva/moodle-block_configurablereports#100]
When using the Import Report From Repository feature, I get the following notices:

    Notice: cr_import_xml(): The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition "object" of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide a __autoload() function to load the class definition in /var/www/blocks/configurable_reports/locallib.php on line 543

    Notice: cr_import_xml(): The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition "object" of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide a __autoload() function to load the class definition in /var/www/blocks/configurable_reports/locallib.php on line 544

In this case, I was attempting to import the "User course completion with Criteria" User type report however it happens with others as well. The report gets created but includes no SQL.

When you go to view the SQL report, you get the following error message:

    Notice: report_sql::create_report(): The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition "object" of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide a __autoload() function to load the class definition in /var/www/blocks/configurable_reports/reports/sql/report.class.php on line 108

I am using:
* Configurable Reports 3.1.1
* Moodle 3.4.2+
* PHP 7.0

Let me know if you need any additional information.

Best regards,

Michael Milette

**Comment by sarjona** [comment]
Hi Michael!

Thanks for reporting this! It has been fixed in the following commit 94c6e5fa7ac9908ec98c635fe32951a9fc085b1c and it will be included in the next version :-)
