### ISSUE TITLE
Make plugin compliant with GDPR

### ISSUE THREAD

**Issue by ilyatregubov** [jleyva/moodle-block_configurablereports#102]
Since Moodle 3.4 there are privacy tests that all plugins should comply to. See https://docs.moodle.org/dev/Privacy_API

**Comment by sarjona** [comment]
Thanks for reporting this issue.

As I've explained in #107 a moment ago, the following commit implements the Privacy API for this block from 3.3 onwards: 7b35af80074c702529ff15d518a8385647fcc1c8

I'll try to publish a new version in the Moodle plugins database once we have a fully functional version for 3.6.
