### ISSUE TITLE
Enrolled students filter issue with db query

### ISSUE THREAD

**Issue by emyb2** [jleyva/moodle-block_configurablereports#109]
When I use the enrolled students filter I get the following error.

<img width="1014" alt="screen shot 2018-12-14 at 4 40 59 pm" src="https://user-images.githubusercontent.com/14080126/49981901-0efb8080-ffbf-11e8-9378-339b38aafe0e.png">

Issue is here - https://github.com/jleyva/moodle-block_configurablereports/blob/MOODLE_30_STABLE/components/filters/enrolledstudents/plugin.class.php#L74 

Fix is to replace the period with a comma.

**Comment by luisdev** [comment]
I'm trying to test this. Can you cllarify what you mean by the "enrolled students filter"?

**Comment by emyb2** [comment]
This is the Enrolled course user filter. #110 addresses this by replacing the concatenation with a comma otherwise the SQL string is being concatenated with an array

<img width="861" alt="screen shot 2019-01-07 at 9 25 45 am" src="https://user-images.githubusercontent.com/14080126/50741150-424bcb00-125e-11e9-9256-fada9871be3c.png">

**Comment by sarjona** [comment]
Thanks! Your patch has been included to fix this issue so it will work properly at the next release! :-)
