### ISSUE TITLE
enable AMOS translations

### ISSUE THREAD

**Issue by nadavkav** [jleyva/moodle-block_configurablereports#11]
Juan,

Please see if you can initiate an English translation for Configurable Reports on the lang.moodle.org (AMOS) translation server/service.

It will enable us (Hebrew users and others) to upload translations and manage them easily.

Nadav :-)

**Comment by jleyva** [comment]
Thanks, you are right, I'm going to upload the English file right now

**Comment by jleyva** [comment]
Hi, the plugin is available in AMOS, I imported also the hebrew translation but it seems to be pending to be resolved by the lang maintainer

**Comment by nadavkav** [comment]
Super cool!!!
Thanks :-)

I am the maintainer (funny) and I have just now approved it (double funny)
