### ISSUE TITLE
Fatal error: Trait 'block_configurable_reports\privacy\core_privacy\local\legacy_polyfill' not found

### ISSUE THREAD

**Issue by dmitriim** [jleyva/moodle-block_configurablereports#111]
Thank you for updating the plugin.

We're testing it in 3.5 and got Fatal error while running unit tests.

vendor/bin/phpunit privacy/tests/provider_test.php

Fatal error: Trait 'block_configurable_reports\privacy\core_privacy\local\legacy_polyfill' not found in /var/www/project/monash35/blocks/configurable_reports/classes/privacy/provider.php on line 55

**Comment by dmitriim** [comment]
I have created a small pull request to fix this issue https://github.com/jleyva/moodle-block_configurablereports/pull/112

**Comment by sarjona** [comment]
Thanks for reporting and fixing this issue!! I've added a commit to fix it! ;-)
