### ISSUE TITLE
Configured block title does not display on course main page

### ISSUE THREAD

**Issue by ebithell** [jleyva/moodle-block_configurablereports#119]
We have found that in Moodle 3.5, users can configure the title of a Configurable Reports block on its settings page but no matter what they set, the default language string is always displayed on the course main page.

It looks as if the way in which blocks set their display title has changed, and requires a different format to be used in specialization(). I've been able to fix this by reference to other blocks where this feature does work, and have attached a patch here.

[configurable_reports.patch.txt](https://github.com/jleyva/moodle-block_configurablereports/files/3173683/configurable_reports.patch.txt)

**Comment by sarjona** [comment]
Thanks a lot, @ebithell for reporting it and providing a patch. I've just pushed a commit which should fix it (https://github.com/jleyva/moodle-block_configurablereports/commit/7e3ff266b7588c5a3307e1ec132c23af5a7749fd). It will be included in the next release.
