### ISSUE TITLE
Moodle 3.3 and lower don't have the interface core_userlist_provider and so gets a fatal error

### ISSUE THREAD

**Issue by kristian-94** [jleyva/moodle-block_configurablereports#125]
The readme says the 3.7.0 release is compatible with moodle 3.3: https://github.com/jleyva/moodle-block_configurablereports/blob/MOODLE_36_STABLE/README.txt#L30

But not completely at least. To see a fatal error:
1. Install the plugin from the MOODLE_36_STABLE branch into a clean moodle 3.3
2. Run `php admin/tool/phpunit/cli/init.php`
3. Run `vendor/bin/phpunit --list-suites` and see a fatal error like the one below:

> root@38c657e39e53:/siteroot# vendor/bin/phpunit --list-suites
> Moodle 3.3.9+ (Build: 20190201), 51ddbfb6818650f5b8538d0a45277f62af2d1f8f
> Php: 7.0.32.0.0.16.04.1, pgsql: 11.1 (Debian 11.1-1.pgdg90+1), OS: Linux 4.15.0-54-generic x86_64
> PHP Fatal error:  Interface 'core_privacy\local\request\core_userlist_provider' not found in /siteroot/blocks/configurable_reports/classes/privacy/provider.php on line 44
> 

Should the readme be updated?

**Comment by sarjona** [comment]
Hi @kristian-94 !

Well spotted! You're right! The core_privacy\local\request\core_userlist_provider interface was added in Moodle 3.4.
I'm planning to publish a new version of the plugin, including some bugs and improvements. I will publish 2 different versions: one for Moodle 3.3 downwards (without the classes/privacy folder) and another for Moodle 3.4 onwards.
Thanks a lot for your contribution!! :-)
