### ISSUE TITLE
upgrade.php is out of sync with install.xml

### ISSUE THREAD

**Issue by Peterburnett** [jleyva/moodle-block_configurablereports#131]
https://github.com/jleyva/moodle-block_configurablereports/blob/MOODLE_36_STABLE/db/upgrade.php#L48
Field global should have default of null, not 0.

https://github.com/jleyva/moodle-block_configurablereports/blob/MOODLE_36_STABLE/db/upgrade.php#L53
Field lastexecutiontime should have default of null, not 0.

https://github.com/jleyva/moodle-block_configurablereports/blob/MOODLE_36_STABLE/db/upgrade.php#L58
Field cron should be NOTNULL

**Comment by Peterburnett** [comment]
It looks like a patch was submitted for this issue in PR #123

**Comment by sarjona** [comment]
I've just integrated the PR that fixes this bug. Thanks a lot for raising it!! :-)
