### ISSUE TITLE
SQL select issue with '_'

### ISSUE THREAD

**Issue by safatshahinsd** [jleyva/moodle-block_configurablereports#137]
The select statement in the SQL selects forcefully removed any '_' in the query.
As an example, 
"select employee as 'profile_field_username'
from prefix_user", this query returns the report as below:
profile field username
username1
username2
.........
The header is forcefully changed to "profile field username" from "profile_field_username".
I figured out the code snippet which is doing it, given below:
moodle/blocks/configurable_reports/reports/sql/report.class.php
The code is given below: (Line 123 - 126)
```
foreach ($rs as $row) {
                    if (empty($finaltable)) {
                        foreach ($row as $colname => $value) {
                            $tablehead[] = str_replace('_', ' ', $colname);
                        }
                    }
```

I want to know the reason behind doing that, and if there is no specific reason, please remove this bit.

**Comment by sarjona** [comment]
Hi @safatshahinsd!
Thanks for reporting this. I've just added a commit (52b029ccefee137a6eb41e1e0db79e3ab078fe6a) in order to remove this "_".
It has helped me also to identify and fix another issue when exporting ODS files.
