### ISSUE TITLE
Incompatible with Moodle 3.8

### ISSUE THREAD

**Issue by pavelsokolov** [jleyva/moodle-block_configurablereports#138]
This block breaks JS in Moodle 3.8, when cachejs is on.

References:
https://moodle.org/mod/forum/discuss.php?d=393570#p1590372
https://tracker.moodle.org/browse/MDL-67327

**Comment by sarjona** [comment]
Thanks for raising this issue!

It will be fixed in https://tracker.moodle.org/browse/MDL-67327, which hopefully will be moved to the main MOODLE_38_STABLE and master branches. So I'm closing this issue (because I've just checked the patch there fixes the issue) ;-)
