### ISSUE TITLE
 Implement a security check for SQL security using the Check API

### ISSUE THREAD

**Issue by Anupamatd** [jleyva/moodle-block_configurablereports#151]
Hi,

Implement a security check for SQL security using the Check API (available in Moodle 3.9) which warns if it is either on, OR if it is not forced off.

Thanks,
Anu

**Comment by yao9394** [comment]
Will submit a PR when https://github.com/jleyva/moodle-block_configurablereports/issues/150 is resolved.

**Comment by jleyva** [comment]
Hi, please follow up in here https://tracker.moodle.org/browse/CONTRIB-8105
