### ISSUE TITLE
FR: For SQL reports exported to another format (CSV, XML, etc.), do not format the text to improve performance

### ISSUE THREAD

**Issue by danowar2k** [jleyva/moodle-block_configurablereports#160]
We have a report using with the Moodle event log table. We ran into a max_execution_limit issue because the report fetched 30000 records and the script took longer than 60 seconds to complete.

I've analyzed the code and found out that this line here:
https://github.com/jleyva/moodle-block_configurablereports/blob/e5be7b0fe94a4b14c6614c7ee58cfe6842b0ec7d/reports/sql/report.class.php#L131
is the culprit. It takes every cell of the resulting recordset and uses format_text, including filters etc.

For small reports this may not be a problem, but large recordsets lead to timeouts.

I understand that cleaning/filtering is necessary when outputting the recordsets to the browser. But is it really necessary to use format_text when exporting a report to  other file formats (CSV, etc.)?

So, if it isn't, please introduce a bool parameter to the report constructor or a method somewhere that introduces a way to turn off the formatting so that exported reports can run faster.

**Comment by danowar2k** [comment]
I already have a pull request ready for this issue and will provide that....

**Comment by danowar2k** [comment]
So, here's my solution for the problem. Works locally, and from my point of view exported reports don't need to be formatted, or do they?

**Comment by luisdev** [comment]
Thanks! I will apply your patch on my dev box and test.

**Comment by luisdev** [comment]
Can you provide testing instructions? I've applied the patch on my dev Moodle but I'm not really sure how to fully test this.

**Comment by danowar2k** [comment]
Well, it would be best tested by doing a huge query. So it would probably be sufficent to fill up a Moodle table (e.g. the logstore_standard_log table where the problem happened for us) with a million or so records (randomly generated, for example).

Then create a SQL query on that table that selects 100.000 records or so.
Then you can test the patch by

* doing the query via the plugin Moodle GUI (display results in DataTable)
* doing the query via directly exporting the report results to CSV via the Moodle GUI (using the CSV export button)

The second case (CSV) should be miles faster than the first, regardless of whether there is sensible data in the generated records.

Was this helpful?
