### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by fxpar** [jleyva/moodle-block_configurablereports#163]
Hi to you all, 

I am not sure the pulling requests have been pulled for a year now.
**Is someone taking it over and using a fork to publish the updates on moodle plugin site?**
Otherwise I am afraid contributions here are never going to be included.
Thanks for your advice.
Cheers
François

**Comment by jleyva** [comment]
Hi,
the project is not abandoned, what happened is that @sarjona was maintaining the plugin as part of his project weeks in Moodle HQ but she was not able to work on it for the 3.9's project week.
I've been accepting some pull requests and making some additional improvements, I expect to release the 3.9 version very soon
