### ISSUE TITLE
SQL report limited to 5000 records

### ISSUE THREAD

**Issue by DBezemer** [jleyva/moodle-block_configurablereports#17]
There is an undocumented "feature" that the SQL report only outputs 5000 records.
Can you create a settings flag for this so you can configure it?

If you like I can make a pull request with the required changes.

David

**Comment by nadavkav** [comment]
Here is a suggested fix
https://github.com/nadavkav/moodle-block_configurablereports/commit/181b56df5372000e2d7d42900cb720be70c8b328

Note: There are some lines of code that slipped into that specific commit. in the English translation file. please ignore them ;-)

**Comment by jleyva** [comment]
Hi,
closing this issue since it was fixed some versions ago (there are now global settings for changing that value)
