### ISSUE TITLE
Can't enter custom SQL

### ISSUE THREAD

**Issue by hoskins-robertj** [jleyva/moodle-block_configurablereports#29]
Using Moodle 2.7.1+ (Build: 20140814) and Configurable Reports 2.3.3 (2011040114).  Essential theme (also tried Clean theme).

When I try to enter a custom SQL query on the "Custom SQL" tab, there is nowhere to type.  I have tried toggling full screen mode, pressing ESC to get out of full screen mode, different browsers (Chrome, FireFox), switching themes (in case my CSS was messing something up), all to no avail.  Here is what I see:
![customsql](https://cloud.githubusercontent.com/assets/8260410/4179360/03fe580c-36c3-11e4-8c0e-5a0340b42eec.jpg)

**Comment by usernamenumber** [comment]
I'm not the maintainer of this project, but for whatever it's worth I'm not seeing this problem. If re-installing the plugin with the latest code doesn't fix it, try checking the Javascript console (in Chrome, right-click->Inspect Element->Console tab) for errors, as well as in your web server's error log if you have access to it.

Did you do a fresh install or an upgrade? I do recall encountering some strange problems when attempting to upgrade, which I had to fix by manually updating the plugin's version in the database afterward.

**Comment by hoskins-robertj** [comment]
Tried it again after I saw your comment and got the same result.  Checked all the settings and it still wouldn't work.

**Comment by usernamenumber** [comment]
Try switching to the default theme and see if that helps. Nothing in the js console or server logs?

**Comment by sarjona** [comment]
Hi @hoskins-robertj !

In order to clean the tracker, I'm going to close this issue because this issue has been inactive during some years and I've not been able to reproduce it in the most recent Moodle versions. Could you please confirm it has been fixed also for you? 
If you're still getting this error, could you please send us more detailed information about how to reproduce it? TIA!
