### ISSUE TITLE
CodeMirror not defined

### ISSUE THREAD

**Issue by jinhofer** [jleyva/moodle-block_configurablereports#38]
When accessing editcomp.php, it loads configurable_reports.js, but not codemirror.js. This causes a background js error to occur when line 13 of configurable_reports.js attempt to call CodeMirror. This can be fixed by commenting out lines 13-38 of configurable_reports.js or including: 

$PAGE->requires->js('/blocks/configurable_reports/js/codemirror/lib/codemirror.js');
$PAGE->requires->css('/blocks/configurable_reports/js/codemirror/lib/codemirror.css');

in editcomp.php.

![image](https://cloud.githubusercontent.com/assets/8837519/5980000/eef80edc-a871-11e4-8048-8a1bd0963755.png)

**Comment by jinhofer** [comment]
I see that there is a new version of your plugin available. Does it include the fix for this, or are you still working on this?

**Comment by jleyva** [comment]
Hi,
sorry I didn't apply the patch you suggested in the last version.

I just committed a patch it to the git repository
