### ISSUE TITLE
Reports are wrongly thought to be on a system context

### ISSUE THREAD

**Issue by pavelsokolov** [jleyva/moodle-block_configurablereports#39]
Problem: when a teacher tries to access any report editing links from managereport.php, he/she never gets access due to missing permissions. 

There are two options why this happens:
1) editing links are missing 'courseid' parameter in URLs therefore editreport.php thinks it is from a system context
2) editreport.php has a default value for courseid=SITEID which forces system context to be used.

I have modified it to grab a 'courseid' value from DB instead of from given URL:

``` php
        if ($id) {
              $courseid = $DB->get_field('block_configurable_reports','courseid',array('id' => $id));
        }
```

This seems to be an inconsistency for me, since none of our teachers has editing rights on a system context, only within courses.

**Comment by jleyva** [comment]
Fixed, thanks!
