### ISSUE TITLE
Requires legacy logging

### ISSUE THREAD

**Issue by colin-umn** [jleyva/moodle-block_configurablereports#40]
Or Moodle admins really like the configurable reports block, but we have not been able to make it work for them in 2.8 because we are not planning to enable legacy logging.  Are there any plans to make this plugin usable to some extent without legacy logging?  Can you suggest any quick workarounds to make it functional without legacy logging enabled?

**Comment by jleyva** [comment]
Hi,
the plugin works now without legacy logging
