### ISSUE TITLE
Which Branch

### ISSUE THREAD

**Issue by jk3us** [jleyva/moodle-block_configurablereports#44]
Which branch should I use if I want to install this plugin with git, CR_23_STABLE?  Will that always be stable or do you also do development on that branch between releases?

It would be nice if you could follow the version convention of using the release date as the version number.  So version 2.3.6 would be 2015050601 instead of 2011040117, which makes it look like it is 4 years old.

**Comment by jleyva** [comment]
Hi,
yes, CR_23_STABLE is the stable version.

Thanks for your feedback about the version number, I'll consider it for the next version

**Comment by jk3us** [comment]
FYI, here is the moodle docs page about the version number, it's a little more detailed than my description. https://docs.moodle.org/dev/version.php
