### ISSUE TITLE
jQuery version conflict

### ISSUE THREAD

**Issue by michael-milette** [jleyva/moodle-block_configurablereports#57]
Good day,

The Moodle theme on our site loads a newer version of jQuery v2.0.3 (2013).

Unfortunately, Configurable Reports subsequently loads its own instance of jQuery 1.2.3 (2011), which is much older than the version the theme is using. This results in conflicts and failures when the theme uses features that didn't exist back then.

Could you please re-write the way jQuery is only loaded by the plugin if it is not already loaded? Here is an untested example of how this might be achieved:

```
<script type="text/javascript">
if (typeof jQuery == 'undefined') {
     document.write(unescape('%3Cscript type="text/javascript" src="../../lib/jquery/jquery-1.11.0.min.js"%3E%3C/script%3E'));
}
</script>
```

You might need some additional code to check the version of jQuery available with a given version of Moodle if that is a concern or just include a more recent version with the plugin.

Best regards,

Michael Milette

**Comment by jleyva** [comment]
Closing this issue since it was fixed integrated the pull request
