### ISSUE TITLE
Question/Pointer - Add additional 'user field value' to permissions

### ISSUE THREAD

**Issue by davidpesce** [jleyva/moodle-block_configurablereports#61]
Curious if you could point me to where I can modify the permissions to allow multiple "user field value". Currently only allows one.

**Comment by davidpesce** [comment]
For anyone curious... to add multiple user field values, modify the following boolean value (set to false):

https://github.com/jleyva/moodle-block_configurablereports/blob/CR_23_STABLE/components/permissions/puserfield/plugin.class.php#L31

**Comment by sarjona** [comment]
Thanks David! I've just integrated your patch! Well spotted!!!! :-)
