### ISSUE TITLE
where is the selected value stored in filters

### ISSUE THREAD

**Issue by davidpesce** [jleyva/moodle-block_configurablereports#64]
@nadavkav

I'm attempting to dynamically load the filters as other filters are selected. But I can't seem to locate where you are storing which filter option is selected. Any pointers?

Including @nadavkav just in case!

**Comment by nadavkav** [comment]
Here is a list of all the filters that are available inside the SQL queries.

And Special filters (if available!):

``` sql
%%FILTER_SEARCHTEXT:table.field:('=', '<', '>', '<=', '>=', '~')%%
%%FILTER_SEMESTER:table.field%%
%%FILTER_YEARNUMERIC:table.field%%
%%FILTER_YEARHEBREW:table.field%%
%%FILTER_COURSES:table.field%%
%%FILTER_MYCOURSE:table.field%%
%%FILTER_CATEGORIES:table.field%%
%%FILTER_SUBCATEGORIES:table.field%%
%%FILTER_ROLE:table.field%%
%%FILTER_STARTTIME:l.time:>%% %%FILTER_ENDTIME:l.time:<%% ('<', '>', '<=', '>=', '~')
%%FILTER_COURSEMODULEID%% , %%FILTER_COURSEMODULEFIELDS%% , %%FILTER_COURSEMODULE%% 
%%FILTER_USERS:table.field%%
%%FILTER_SYSTEMUSER:table.field%%
%%FILTER_COURSEUSER:table.field%%
%%FILTER_COURSEENROLLEDSTUDENTS:table.field%%
```

Now, suppose you add the "Search Text" filter to the report, then, you will be able to use the following code in the WHERE SQL statement like this:

``` sql
SELECT * FROM mdl_user AS "user"
WHERE 1=1
%%FILTER_SEARCHTEXT:user.firstname:~%%
```

Which will be transformed into:

``` sql
SELECT * FROM mdl_user AS "user"
WHERE 1=1
AND user.firstname LIKE '%Your-search-text-goes-here%'
```

Hope it helps.

**Comment by nadavkav** [comment]
When you actually run the report, you are passing HTTP GET input param variable to the php page, and with the above example (the "Search text" filter) you are using the following code:
https://github.com/jleyva/moodle-block_configurablereports/blob/CR_23_STABLE/components/filters/searchtext/plugin.class.php
And the $filter_searchtext variable to store the user's input that is used to filter the SQL query.

**Comment by davidpesce** [comment]
I'm a bit past that. I'm using 4 custom profile fields as filters. I want each filter (after selected) to limit the values available in the next. What I can't figure out is where the "selected" value is stored. If I can reference that, then I can limit the remaining filters.

**Comment by nadavkav** [comment]
I see...
You will have to use some ajax for that.
Add onchange js code to the first input element (filter) and call an ajax function that retrieve the second input element (select) items (options) from a php script, and on success event, populate the second filter.

**Comment by nadavkav** [comment]
Checkout:
https://github.com/moodle/moodle/blob/master/group/index.php#L171
and:
https://github.com/moodle/moodle/blob/master/group/clientlib.js#L129

**Comment by davidpesce** [comment]
The plugin uses JQuery's tablesorter. I'm going to go that route and see if I can get the functionality via a more recent version.

**Comment by davidpesce** [comment]
@nadavkav - btw, I forked this and made some modifications under a branch called DFU. Not sure if you need any of the functionality. The biggest one for me was multiple fuserfields!

**Comment by nadavkav** [comment]
Interesting. (what are you using it for?)

**Comment by davidpesce** [comment]
Using it to include multiple user fields in the permissions. I have reports that need to be available to certain users that don't share a common field. So this allows me to put OR between them all.

**Comment by nadavkav** [comment]
Interesting. but you already have OR available between filters.

**Comment by davidpesce** [comment]
Agreed, but you could only select one fuserfield. Once you added one fuserfield, you couldn't add another.

**Comment by nadavkav** [comment]
Yep. right :-(
