### ISSUE TITLE
403 Error while installing on Moodle 3

### ISSUE THREAD

**Issue by Krutie** [jleyva/moodle-block_configurablereports#67]
I get 403 Error while upgrading this plugin to its latest version on Moodle 3.0
Tried several previous versions of the plugin and got the same 403 Error on Moodle 3.0 
Please see the screenshot attached. 
![403-config-report-error](https://cloud.githubusercontent.com/assets/19180970/15005405/6a03321e-1207-11e6-9075-c4eb22201786.JPG)

**Comment by sarjona** [comment]
Hi @Krutie!
Sorry for the late reply. Are you still having this issue? I've not been able to reproduce it and I can't see why it should be related to the configurable reports plugin.
TIA!
