### ISSUE TITLE
Moodle 3.0 branch, JS broken.

### ISSUE THREAD

**Issue by danmarsden** [jleyva/moodle-block_configurablereports#69]
I'm seeing these errors:
..blocks/configurable_reports/js/datatables/media/js/jquery.js Failed to load resource: the server responded with a status of 404 (Not Found)

seems to be caused by:
3c218a9a49e3a25e46c2289c4a038b1d271d5ed5

Where the file media/js/jquery.js is deleted but the path is not updated to point to the core jquery file correctly. 

This prevents all the js sorting stuff from working.

**Comment by danmarsden** [comment]
to fix this it looks like we just need to add:
$PAGE->requires->jquery();

to the viewreport.php

**Comment by jleyva** [comment]
Thanks Dan!

I fixed it, I'll be publishing a new version today
