### ISSUE TITLE
Report Dies if it is too large. Hitting PHP Memory Limit

### ISSUE THREAD

**Issue by alex-rowe** [jleyva/moodle-block_configurablereports#71]
We edited a report which on trying to export gives an error message (with debugging turned on) of

```
PHP Fatal Error: Allowed Memory Size of X Bytes Exhausted
```

due to the amount of data the report is generating. This was for a CSV export as well.

To get around this, we added the Moodle `raise_memory_limit()` function to `viewreport.php` on line 109 as below.

```
    } else {
        raise_memory_limit(MEMORY_HUGE);
        $exportplugin = $CFG->dirroot.'/blocks/configurable_reports/export/'.$format.'/export.php';
        if (file_exists($exportplugin)) {
            require_once($exportplugin);
            export_report($reportclass->finalreport);
        }
        die;
```

If you would like me to submit a Pull Request, let me know, otherwise this could be added quite easily and would be helpful when needing a report with a lot of data.

Thanks
Alex

**Comment by sarjona** [comment]
Hi Alex!
Thanks for reporting this and sharing a solution. I've added a commit with your patch (and an extra line to raise the time): d97cafff8e2f0254a850eb449bd170368c1b1a0c
Cheers!
