### ISSUE TITLE
Configurable reports: Display Global reports by default

### ISSUE THREAD

**Issue by benIT** [jleyva/moodle-block_configurablereports#81]
When you add a new block instance, the block instance has no `config` property, so the line  if `(!empty($this->config->displayglobalreports))` is evaluated to false and global reports are not displayed.
This behavior is quiete confusing for new users that create global reports and don't see them in the block!
2 recent topics about that on the forum:
 - [https://moodle.org/mod/forum/discuss.php?d=348560#p1414583](https://moodle.org/mod/forum/discuss.php?d=348560#p1414583)
 - [https://moodle.org/mod/forum/discuss.php?d=350404#p1414058](https://moodle.org/mod/forum/discuss.php?d=350404#p1414058)

You need to manually edit the block settings so the `$this->config->displayglobalreport` can be set to true, and then global reports are available!

The fix is quite easy, let's say that in `specialization`  of `block_configurable_reports.php`, when there is no config, let's set to true the `displayglobalreports` option as follow:
 

```
   /**
     * Act on instance data.
     */
    public function specialization()
    {

        if ($this->config) {
            $this->title = $this->config->title ? get_string('pluginname', 'block_configurable_reports') : $this->config->title;
        } else {
            $this->config = new stdClass();
            $this->config->displayglobalreports = true;
        }
    }
```

**Comment by benIT** [comment]
pull request just delivered!

**Comment by sarjona** [comment]
In order to clean the tracker, I'm going to close this issue because it was integrated some years ago :-)

Thanks for your contribution @benIT
