### ISSUE TITLE
Configurable reports: JSON exporter feature request

### ISSUE THREAD

**Issue by benIT** [jleyva/moodle-block_configurablereports#83]
This request deals with adding a JSON exporter for configurable reports. 

There are ODS, CSV, XLS exports but not JSON. This would be very handy to have a JSON export, especially to process exported data with other tools.

**Comment by benIT** [comment]
[pull reques](https://github.com/jleyva/moodle-block_configurablereports/pull/84)t delivered!

**Comment by sarjona** [comment]
In order to clean the tracker, I'm going to close this issue because it was integrated some years ago :-)

Thanks for your contribution @benIT

**Comment by benIT** [comment]
you're welcome @sarjona . Have a nice day.
