### ISSUE TITLE
Configurable report: Moodle 3.3

### ISSUE THREAD

**Issue by gemguardian** [jleyva/moodle-block_configurablereports#90]
Hello Juan, 

I installed Configurable reports on a test Moodle 3.3 (PHP 5.6.30) without issues. It evens seems to run the reports fine. But I have one small line of text when it shows "View Reports" - it seems to be in the javascript. 

![clipboard01](https://user-images.githubusercontent.com/16559999/28014222-26011266-656c-11e7-9b06-a5dd066beffb.png)

===

        function printDiv(id){
            var cdiv, tmpw;

            cdiv = document.getElementById(id);
            tmpw = window.open(" ","Print");

            tmpw.document.open();
            tmpw.document.write('<html><body>');
            tmpw.document.write(cdiv.innerHTML);
            tmpw.document.write('  <div id="bitnami-banner" data-banner-id="a36d2">  <style>#bitnami-banner {z-index:100000;height:80px;padding:0px;width:120px;background:transparent;position:fixed;right:0px;bottom:0px;border:0px solid #EDEDED;} #bitnami-banner .bitnami-corner-image-div {position:fixed;right:0px;bottom:0px;border:0px;z-index:100001;height:110px;} #bitnami-banner .bitnami-corner-image-div .bitnami-corner-image {position:fixed;right:0px;bottom:0px;border:0px;z-index:100001;height:110px;} #bitnami-close-banner-button {height:12px;width:12px;z-index:10000000000;position:fixed;right:5px;bottom:65px;display:none;cursor:pointer}</style>  <img id="bitnami-close-banner-button" src="/bitnami/images/close.png"/>  <div class="bitnami-corner-image-div">     <a href="/bitnami/index.html" target="_blank">       <img class="bitnami-corner-image" alt="Bitnami" src="/bitnami/images/corner-logo.png"/>     </a>  </div>  <script type="text/javascript" src="/bitnami/banner.js"> 
==

I am not sure how easy it is to fix this, but I hope you find some time through out the Moodle Desktop/Moodle Mobile to fix this. 

If I need to contact someone else then please let me know. 

Gemma

**Comment by sarjona** [comment]
Hola Gemma!

Thanks for reporting this and my apologies for the late reply.

Are you still having this issue? I've not been able to reproduce it in Moodle 3.6. If this is still happening, could you please add more information such as replication instructions and Moodle and plugin versions? It will help to reproduce the issue and try to fix it :-) TIA!

**Comment by gemguardian** [comment]
hi Sarjona,

I am not using 3.6 yet, mostly on 3.5 I have some issues there, though just installed the latest release version on my local install and I had no issues. 

You have made me one happy user - since it was causing issues at one of my sites, but with this update it might just be solved. 

Thank you so much for your work!Really appricate this. 
Gem

**Comment by sarjona** [comment]
Hi Gem!
Thanks for your feedback! I'm happy also to know that the new version has fixed it! :-)
In order to clean the tracker, I'm going to close this issue
Cheers!
Sara
