### ISSUE TITLE
Configurable reports causes 404 errors on every Moodle page

### ISSUE THREAD

**Issue by amandadoughty** [jleyva/moodle-block_configurablereports#95]
Discussion and fix here:

https://moodle.org/mod/forum/discuss.php?d=351496

**Comment by michael-milette** [comment]
The following solution works regardless of whether Moodle is installed in the webroot or in a sub-folder.

Replace the following lines:

    @import url("../blocks/configurable_reports/js/datatables/media/css/jquery.dataTables.css");
    @import url("../blocks/configurable_reports/js/codemirror/lib/codemirror.css");
    @import url("../blocks/configurable_reports/js/codemirror/addon/display/fullscreen.css");

With this:

    @import url("../../../../blocks/configurable_reports/js/datatables/media/css/jquery.dataTables.css");
    @import url("../../../../blocks/configurable_reports/js/codemirror/lib/codemirror.css");
    @import url("../../../../blocks/configurable_reports/js/codemirror/addon/display/fullscreen.css");

I tested this with Configurable Reports 3.1.1 (2016020103) on Moodle 3.4 using Chrome, Firefox, Edge and Internet Explorer.

Let me know if it doesn't work for you.

Best regards,

Michael Milette

**Comment by michael-milette** [comment]
This has been addressed in pull request https://github.com/jleyva/moodle-block_configurablereports/pull/93

**Comment by sarjona** [comment]
Thanks for reporting this Michael. 

The content of this files has been included in the styles.css (as documented in readme_moodle.txt): 8d7499bff8f4fa4b39418e10c08b016521448633 so this issue should be fixed in the https://github.com/jleyva/moodle-block_configurablereports/commits/MOODLE_36_STABLE branch
